In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from stockstats import StockDataFrame as Sdf
from ta import *
%matplotlib inline

#stock = pd.read_csv('MSFT_80s_temp3.csv')
stock = pd.read_csv('dow_jones.csv')
#stock = pd.read_csv('JPM_80s.csv')
output = stock

"""

# Converter para dados semanais

stock['Date'] = pd.to_datetime(stock['Date'])
stock.set_index('Date', inplace=True)
stock.sort_index(inplace=True)

def take_first(array_like):
    return array_like[0]

def take_last(array_like):
    return array_like[-1]

output = stock.resample('W',                                 # Weekly resample
                    how={'Open': take_first, 
                         'High': 'max',
                         'Low': 'min',
                         'Close': take_last,
                         'Volume': 'sum'}, 
                    loffset=pd.offsets.timedelta(days=-6))  # to put the labels to Monday

output = stock
output = output[['Open', 'High', 'Low', 'Close', 'Volume']]# Converter para dados semanais

stock['Date'] = pd.to_datetime(stock['Date'])
stock.set_index('Date', inplace=True)
stock.sort_index(inplace=True)

def take_first(array_like):
    return array_like[0]

def take_last(array_like):
    return array_like[-1]

output = stock.resample('W',                                 # Weekly resample
                    how={'Open': take_first, 
                         'High': 'max',
                         'Low': 'min',
                         'Close': take_last,
                         'Volume': 'sum'}, 
                    loffset=pd.offsets.timedelta(days=-6))  # to put the labels to Monday

output = stock
output = output[['Open', 'High', 'Low', 'Close', 'Volume']]
"""

"\n\n# Converter para dados semanais\n\nstock['Date'] = pd.to_datetime(stock['Date'])\nstock.set_index('Date', inplace=True)\nstock.sort_index(inplace=True)\n\ndef take_first(array_like):\n    return array_like[0]\n\ndef take_last(array_like):\n    return array_like[-1]\n\noutput = stock.resample('W',                                 # Weekly resample\n                    how={'Open': take_first, \n                         'High': 'max',\n                         'Low': 'min',\n                         'Close': take_last,\n                         'Volume': 'sum'}, \n                    loffset=pd.offsets.timedelta(days=-6))  # to put the labels to Monday\n\noutput = stock\noutput = output[['Open', 'High', 'Low', 'Close', 'Volume']]# Converter para dados semanais\n\nstock['Date'] = pd.to_datetime(stock['Date'])\nstock.set_index('Date', inplace=True)\nstock.sort_index(inplace=True)\n\ndef take_first(array_like):\n    return array_like[0]\n\ndef take_last(array_like):\n    return array_like[-1]\n\noutput = stock.resample('W',                                 # Weekly resample\n                    how={'Open': take_first, \n                         'High': 'max',\n                         'Low': 'min',\n                         'Close': take_last,\n                         'Volume': 'sum'}, \n                    loffset=pd.offsets.timedelta(days=-6))  # to put the labels to Monday\n\noutput = stock\noutput = output[['Open', 'High', 'Low', 'Close', 'Volume']]\n"

In [2]:
output.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89604 entries, 0 to 89603
Data columns (total 7 columns):
Date         89604 non-null object
Open         89604 non-null float64
High         89604 non-null float64
Low          89604 non-null float64
Close        89604 non-null float64
Adj Close    89604 non-null float64
Volume       89604 non-null int64
dtypes: float64(5), int64(1), object(1)
memory usage: 4.8+ MB

In [3]:
output.head(10)

         Date      Open      High       Low     Close  Adj Close    Volume
0  1980-01-02  0.718750  0.721354  0.703125  0.703125   0.018480   3451200
1  1980-01-03  0.703125  0.723958  0.697917  0.721354   0.018959   3960000
2  1980-01-04  0.721354  0.729167  0.718750  0.729167   0.019165   1694400
3  1980-01-07  0.729167  0.731771  0.723958  0.726563   0.019096   4396800
4  1980-01-08  0.726563  0.734375  0.726563  0.731771   0.019233   3244800
5  1980-01-09  0.731771  0.744792  0.729167  0.736979   0.019370  11568000
6  1980-01-10  0.736979  0.744792  0.731771  0.736979   0.019370  19444800
7  1980-01-11  0.736979  0.750000  0.734375  0.739583   0.019438   6240000
8  1980-01-14  0.739583  0.744792  0.729167  0.736979   0.019370   2145600
9  1980-01-15  0.736979  0.736979  0.718750  0.723958   0.019028   7560000

In [4]:
# Utilizando a livaria 'ta'

# Add bollinger band high indicator filling NaN values
output['bb_high_indicator'] = bollinger_hband_indicator(output["Close"], n=20, ndev=2, fillna=True)

# Add bollinger band low indicator filling NaN values
output['bb_low_indicator'] = bollinger_lband_indicator(output["Close"], n=20, ndev=2, fillna=True)

# Adicionar Money Flow Index
output['MoneyFlowIndex'] = money_flow_index(output["High"],output["Low"],output["Close"],output["Volume"],n=14, fillna=True)

# Adicionar AwesomeOscillator
output['AwesomeOscillator'] = ao(output["High"],output["Low"], s=5, l=34, fillna=True)

# Adicionar Stochatic Oscillator
output['StochaticOscillator'] = stoch(output["High"],output["Low"],output["Close"], n=14, fillna=True)

# Adicionar Stochatic Oscillator Signal
output['StochaticOscillatorSignal'] = stoch_signal(output["High"],output["Low"],output["Close"], n=14, d_n=3, fillna=True)

# Adicionar True Strength Index
output['TrueStrengthIndex'] = tsi(output["Close"], r=25, s=13, fillna=True)

# Adicionar Ultimate Oscillator
output['UltimateOscillator'] = uo(output["High"],output["Low"],output["Close"], s=7, m=14, l=28, ws=4.0, wm=2.0, wl=1.0, fillna=True)

# Adicionar William % R
output['William%R'] = wr(output["High"],output["Low"],output["Close"], lbp=14, fillna=True)

# Adicionar RSI
output['RSI'] = rsi(output["Close"], n=14, fillna=True)

In [5]:
# Adicionar features (MM4,MM9,MM18) e uma label (1=Subiu, 0=Desceu)

output['Change'] = output['Close'].pct_change()
#UP se percentagem 'maior ou igual a 0,6%'

#output['UP'] = np.where(output['Change'] < -0.005 ,1.0,0.0) 

output['UP'] = np.where(output['Change'] > 0.00, 1, 0)
output['MM4'] = output['Close'].rolling(window=4).mean()
output['MM9'] = output['Close'].rolling(window=9).mean()
output['MM18'] = output['Close'].rolling(window=18).mean()
output['CrossMM'] = np.where(output['MM4'] > output['MM18'],1.0,0.0)
output['CrossPrice'] = np.where(output['Open'] > output['MM18'],1.0,0.0)

In [6]:
output.head(5)

,Date,Open,High,Low,Close,Adj Close,Volume,bb_high_indicator,bb_low_indicator,MoneyFlowIndex,...,UltimateOscillator,William%R,RSI,Change,UP,MM4,MM9,MM18,CrossMM,CrossPrice
0,1980-01-02,0.718750,0.721354,0.703125,0.703125,0.018480,3451200,0.0,0.0,50.0,...,50.0,-50.0,50.000000,NaN,0,NaN,NaN,NaN,0.0,0.0
1,1980-01-03,0.703125,0.723958,0.697917,0.721354,0.018959,3960000,0.0,0.0,50.0,...,50.0,-50.0,100.000000,0.025926,1,NaN,NaN,NaN,0.0,0.0
2,1980-01-04,0.721354,0.729167,0.718750,0.729167,0.019165,1694400,0.0,0.0,50.0,...,50.0,-50.0,100.000000,0.010831,1,NaN,NaN,NaN,0.0,0.0
3,1980-01-07,0.729167,0.731771,0.723958,0.726563,0.019096,4396800,0.0,0.0,50.0,...,50.0,-50.0,88.711278,-0.003571,0,0.720052,NaN,NaN,0.0,0.0
4,1980-01-08,0.726563,0.734375,0.726563,0.731771,0.019233,3244800,0.0,0.0,50.0,...,50.0,-50.0,91.044315,0.007168,1,0.727214,NaN,NaN,0.0,0.0

In [7]:
# Preencher os dados em falta

media4 = output['MM4'].mean()
media9 = output['MM9'].mean()
media18 = output['MM18'].mean()

output['MM4'].fillna(media4, inplace=True)
output['MM9'].fillna(media9, inplace=True)
output['MM18'].fillna(media18, inplace=True)
output['Change'].fillna(0, inplace=True)

In [8]:
output.head(15)

,Date,Open,High,Low,Close,Adj Close,Volume,bb_high_indicator,bb_low_indicator,MoneyFlowIndex,...,UltimateOscillator,William%R,RSI,Change,UP,MM4,MM9,MM18,CrossMM,CrossPrice
0,1980-01-02,0.718750,0.721354,0.703125,0.703125,0.018480,3451200,0.0,0.0,50.000000,...,50.0,-50.000000,50.000000,0.000000,0,36.396759,36.397601,36.399115,0.0,0.0
1,1980-01-03,0.703125,0.723958,0.697917,0.721354,0.018959,3960000,0.0,0.0,50.000000,...,50.0,-50.000000,100.000000,0.025926,1,36.396759,36.397601,36.399115,0.0,0.0
2,1980-01-04,0.721354,0.729167,0.718750,0.729167,0.019165,1694400,0.0,0.0,50.000000,...,50.0,-50.000000,100.000000,0.010831,1,36.396759,36.397601,36.399115,0.0,0.0
3,1980-01-07,0.729167,0.731771,0.723958,0.726563,0.019096,4396800,0.0,0.0,50.000000,...,50.0,-50.000000,88.711278,-0.003571,0,0.720052,36.397601,36.399115,0.0,0.0
4,1980-01-08,0.726563,0.734375,0.726563,0.731771,0.019233,3244800,0.0,0.0,50.000000,...,50.0,-50.000000,91.044315,0.007168,1,0.727214,36.397601,36.399115,0.0,0.0
5,1980-01-09,0.731771,0.744792,0.729167,0.736979,0.019370,11568000,0.0,0.0,50.000000,...,50.0,-50.000000,92.768721,0.007117,1,0.731120,36.397601,36.399115,0.0,0.0
6,1980-01-10,0.736979,0.744792,0.731771,0.736979,0.019370,19444800,0.0,0.0,50.000000,...,50.0,-50.000000,92.768721,0.000000,0,0.733073,36.397601,36.399115,0.0,0.0
7,1980-01-11,0.736979,0.750000,0.734375,0.739583,0.019438,6240000,0.0,0.0,50.000000,...,50.0,-50.000000,93.590292,0.003533,1,0.736328,36.397601,36.399115,0.0,0.0
8,1980-01-14,0.739583,0.744792,0.729167,0.736979,0.019370,2145600,0.0,0.0,50.000000,...,50.0,-50.000000,82.743272,-0.003521,0,0.737630,0.729167,36.399115,0.0,0.0
9,1980-01-15,0.736979,0.736979,0.718750,0.723958,0.019028,7560000,0.0,0.0,50.000000,...,50.0,-50.000000,49.585487,-0.017668,0,0.734375,0.731481,36.399115,0.0,0.0
10,1980-01-16,0.718750,0.718750,0.700521,0.700521,0.018412,12033600,0.0,0.0,50.000000,...,50.0,-50.000000,27.062491,-0.032373,0,0.725260,0.729167,36.399115,0.0,0.0
11,1980-01-17,0.700521,0.708333,0.684896,0.687500,0.018070,4377600,0.0,0.0,50.000000,...,50.0,-50.000000,20.959500,-0.018588,0,0.712240,0.724537,36.399115,0.0,0.0
12,1980-01-18,0.687500,0.692708,0.682292,0.684896,0.018001,5121600,0.0,0.0,50.000000,...,50.0,-50.000000,19.922762,-0.003788,0,0.699219,0.719907,36.399115,0.0,0.0
13,1980-01-21,0.687500,0.703125,0.687500,0.697917,0.018343,3892800,0.0,0.0,46.811632,...,50.0,-76.922963,37.702011,0.019012,1,0.692708,0.716146,36.399115,0.0,0.0
14,1980-01-22,0.697917,0.708333,0.690104,0.690104,0.018138,6724800,0.0,0.0,42.621374,...,50.0,-88.462220,32.678696,-0.011195,0,0.690104,0.710937,36.399115,0.0,0.0

In [9]:
output.tail(5)

,Date,Open,High,Low,Close,Adj Close,Volume,bb_high_indicator,bb_low_indicator,MoneyFlowIndex,...,UltimateOscillator,William%R,RSI,Change,UP,MM4,MM9,MM18,CrossMM,CrossPrice
89599,2019-02-11,42.279999,42.310001,41.509998,41.680000,41.680000,25713600,0.0,0.0,47.085568,...,52.738289,-39.452049,45.892685,-0.013024,0,41.985001,42.155556,41.823889,1.0,1.0
89600,2019-02-12,41.709999,42.009998,41.389999,41.869999,41.869999,28975500,0.0,0.0,53.560604,...,53.410363,-34.246594,48.614996,0.004559,1,41.870000,42.187778,41.810556,1.0,0.0
89601,2019-02-13,41.919998,42.060001,41.389999,41.700001,41.700001,23488800,0.0,0.0,54.727806,...,54.405187,-38.904076,46.214503,-0.004060,0,41.870000,42.104445,41.767778,1.0,1.0
89602,2019-02-14,41.700001,42.119999,41.619999,41.970001,41.970001,18847200,0.0,0.0,61.706190,...,59.565226,-31.506812,50.677655,0.006475,1,41.805000,42.003334,41.736667,1.0,0.0
89603,2019-02-15,42.380001,42.509998,42.080002,42.400002,42.400002,18186900,0.0,0.0,69.632965,...,60.568364,-19.725956,57.203520,0.010245,1,41.985001,41.998890,41.743889,1.0,1.0

In [10]:
output.UP = output.UP.shift(1)
output['UP'].fillna(1,inplace=True)
output.head()

,Date,Open,High,Low,Close,Adj Close,Volume,bb_high_indicator,bb_low_indicator,MoneyFlowIndex,...,UltimateOscillator,William%R,RSI,Change,UP,MM4,MM9,MM18,CrossMM,CrossPrice
0,1980-01-02,0.718750,0.721354,0.703125,0.703125,0.018480,3451200,0.0,0.0,50.0,...,50.0,-50.0,50.000000,0.000000,1.0,36.396759,36.397601,36.399115,0.0,0.0
1,1980-01-03,0.703125,0.723958,0.697917,0.721354,0.018959,3960000,0.0,0.0,50.0,...,50.0,-50.0,100.000000,0.025926,0.0,36.396759,36.397601,36.399115,0.0,0.0
2,1980-01-04,0.721354,0.729167,0.718750,0.729167,0.019165,1694400,0.0,0.0,50.0,...,50.0,-50.0,100.000000,0.010831,1.0,36.396759,36.397601,36.399115,0.0,0.0
3,1980-01-07,0.729167,0.731771,0.723958,0.726563,0.019096,4396800,0.0,0.0,50.0,...,50.0,-50.0,88.711278,-0.003571,1.0,0.720052,36.397601,36.399115,0.0,0.0
4,1980-01-08,0.726563,0.734375,0.726563,0.731771,0.019233,3244800,0.0,0.0,50.0,...,50.0,-50.0,91.044315,0.007168,0.0,0.727214,36.397601,36.399115,0.0,0.0

In [11]:
output.keys()

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume',
       'bb_high_indicator', 'bb_low_indicator', 'MoneyFlowIndex',
       'AwesomeOscillator', 'StochaticOscillator', 'StochaticOscillatorSignal',
       'TrueStrengthIndex', 'UltimateOscillator', 'William%R', 'RSI', 'Change',
       'UP', 'MM4', 'MM9', 'MM18', 'CrossMM', 'CrossPrice'],
      dtype='object')

In [12]:
output.to_csv('dow_jones_up_nextday.csv')

In [13]:
corr_matrix = output.corr()
corr_matrix["UP"].sort_values(ascending=False)

UP                           1.000000
RSI                          0.332973
StochaticOscillator          0.309453
William%R                    0.309453
CrossPrice                   0.254527
StochaticOscillatorSignal    0.237688
MoneyFlowIndex               0.236465
UltimateOscillator           0.215754
bb_high_indicator            0.168448
CrossMM                      0.117072
TrueStrengthIndex            0.037346
Low                          0.031404
Open                         0.030952
Close                        0.030755
High                         0.030523
Adj Close                    0.029494
AwesomeOscillator            0.026123
MM4                          0.025677
MM9                          0.023190
MM18                         0.022231
Volume                       0.006663
Change                       0.000101
bb_low_indicator            -0.141648
Name: UP, dtype: float64

In [14]:
# Split train/sets
from sklearn.model_selection import train_test_split

# Criar tabela com 'features', e com respectiva label (UP)
y = output['UP']
#X = output[['RSI','Volume','MoneyFlowIndex','bb_high_indicator','CrossMM']]
X = output[['Volume','High','Low','RSI','CrossMM','CrossPrice','bb_high_indicator','MoneyFlowIndex','Open','MM4','MM9','MM18','StochaticOscillator', 'William%R', 'UltimateOscillator', 'StochaticOscillatorSignal' ]]

#X = output.drop(['UP'],axis=1)
#Split 
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=42)

In [15]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(67203, 16)
(22401, 16)
(67203,)
(22401,)

In [16]:
X_test.tail()

,Volume,High,Low,RSI,CrossMM,CrossPrice,bb_high_indicator,MoneyFlowIndex,Open,MM4,MM9,MM18,StochaticOscillator,William%R,UltimateOscillator,StochaticOscillatorSignal
49716,4991800,36.187500,35.093750,41.803983,0.0,0.0,0.0,47.917077,36.000000,35.898437,35.944444,37.022569,18.919340,-81.080660,49.328109,28.501303
68493,9045000,36.799999,36.310001,36.889427,0.0,0.0,0.0,52.295752,36.450001,36.800001,37.143333,37.361111,18.224299,-81.775701,46.884252,11.785514
82992,7225200,6.447917,6.333333,55.536552,1.0,1.0,0.0,57.755393,6.427083,6.351563,6.268519,6.249421,58.695611,-41.304389,57.306056,77.626665
84144,12261600,17.854166,17.125000,81.487597,1.0,1.0,1.0,55.270836,17.145834,17.244792,17.115741,16.946759,98.529505,-1.470495,63.632821,81.623694
72044,10136700,80.820000,80.300003,51.234977,0.0,0.0,0.0,54.987681,80.339996,80.324999,80.248889,80.518889,68.944109,-31.055891,52.858353,66.770197

In [17]:
y_test.tail()

49716    1.0
68493    0.0
82992    1.0
84144    1.0
72044    1.0
Name: UP, dtype: float64

In [18]:
#Scaling
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train_sca = sc.fit_transform(X_train)
X_test_sca = sc.transform(X_test)

In [19]:
X_train_sca

array([[-0.10384951,  0.24958081,  0.25817738, ...,  1.39254967,
         0.50064449,  1.12285875],
       [ 2.81028078, -0.86461125, -0.86293014, ..., -0.24554092,
         0.17460128, -0.15334186],
       [ 0.11720184,  0.54613202,  0.53922898, ...,  0.66766687,
         0.42792635,  0.1527303 ],
       ...,
       [ 1.07235445, -0.17580815, -0.17686812, ...,  0.7375069 ,
         2.49210841,  1.20123264],
       [-0.00681925, -0.88501038, -0.88375347, ..., -1.72792002,
        -1.73165872, -1.50926052],
       [-0.57031737, -0.85197804, -0.85004789, ...,  0.45045746,
         0.12945599,  0.64462199]])

In [20]:
### Escolher o modelo (Logistic Regression), fit model(treinar o modelo), efectuar previsões, e medir resultados)
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

#Escolher modelo

log_reg = LogisticRegression(C=100)
#Treinar o modelo(fit model)
log_reg.fit(X_train_sca,y_train)
#Efectuar previsões
y_pred = log_reg.predict(X_test_sca)
#Medir resultados previstos com os dados reais

print('Accuracy Score:', accuracy_score(y_test,y_pred))
#print('X_test_sca:', X_test_sca[-1])
print('Valores Reais: \n', y_test[17350:17360])
print('Valores Calculados: ', y_pred[17350:17360])

Accuracy Score: 0.72934244007
Valores Reais:
 61520    1.0
330      0.0
88273    0.0
83406    0.0
30165    1.0
15943    1.0
23338    1.0
59686    1.0
34180    0.0
84155    1.0
Name: UP, dtype: float64
Valores Calculados:  [ 1.  0.  1.  0.  1.  1.  0.  1.  1.  1.]

In [21]:
# Confusion matrix : Dados Train

from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix

# Efectuar uma previsão
y_train_pred_log = cross_val_predict(log_reg, X_train_sca, y_train, cv=3)

# calcular confusion matrix entre a previsão anterior e os resultados reais(y_train)
confusion_matrix(y_train,y_train_pred_log)

array([[25433,  8795],
       [ 9346, 23629]])

In [22]:
# Confusion matrix : Dados Teste

from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix

# Efectuar uma previsão
y_test_pred_log = cross_val_predict(log_reg, X_test_sca, y_test, cv=3)

# calcular confusion matrix entre a previsão anterior e os resultados reais(y_train)
confusion_matrix(y_test,y_test_pred_log)

array([[8422, 2989],
       [3145, 7845]])

In [23]:
# F1_score - (precision and recall: dados train)

from sklearn.metrics import precision_score, recall_score, f1_score

print('Performance de acertos: ',precision_score(y_train, y_train_pred_log))
print('True Positive Rate: ',recall_score(y_train,y_train_pred_log))
print('F1 Score: ',f1_score(y_train, y_train_pred_log))

Performance de acertos:  0.728750308414
True Positive Rate:  0.716573161486
F1 Score:  0.722610437468

In [24]:
import pickle

In [25]:
with open('meu_modelo_next_day_up','wb') as f:
    pickle.dump(log_reg,f)